# Bonus Poin 1: Menggunakan Multi-Agent (AutoGen)

Bagian ini merupakan penyelesaian untuk **Bonus Poin 1** dari Mini Proyek 2, yaitu menggunakan platform multi-agent (seperti **AutoGen**) untuk melakukan penilaian terhadap jawaban essay siswa.

### Penjelasan Sistem Multi-Agent
Dalam sistem ini, kita akan membuat sebuah grup diskusi (*Group Chat*) yang terdiri dari beberapa agen AI untuk mengevaluasi setiap essay secara kolaboratif:
1. **Admin**: Bertugas memberikan essay kepada agen lain untuk dinilai.
2. **Penilai Utama**: Bertugas menganalisis tata bahasa dan isi essay, lalu memberikan perkiraan skor.
3. **Reviewer Senior**: Bertugas membaca analisis dari Penilai Utama dan memberikan keputusan mutlak berupa skor final (1-6).

Dengan pendekatan ini, penilaian diharapkan menjadi lebih objektif karena melalui proses diskusi dan review layaknya manusia.

### 1. Inisialisasi Agen (Admin, Penilai Utama, Reviewer Senior)
Pada tahap ini, kita mendefinisikan masing-masing agen dengan instruksi spesifik (*system message*) agar mereka tahu perannya. Kita menggunakan Ollama secara lokal sebagai backend LLM.

In [1]:
import autogen
import pandas as pd
from tqdm import tqdm
import re

# 1. Konfigurasi Ollama untuk AutoGen (Gunakan endpoint kompatibel OpenAI milik Ollama)
llm_config = {
    "config_list": [
        {
            "model": "llama3",
            "base_url": "http://localhost:11434/v1",
            "api_key": "ollama-local" # Wajib diisi meskipun dengan teks sembarang
        }
    ],
    "temperature": 0.1
}

# 2. Membuat Agen 1: Penilai Utama
penilai = autogen.AssistantAgent(
    name="Penilai_Utama",
    system_message="""Anda adalah Guru Penilai. Tugas Anda menganalisis esai yang diberikan dan memberikan perkiraan skor (1-6). 
    Berikan analisis singkat maksimal 3 kalimat mengenai tata bahasa dan isi esai, lalu akhiri dengan perkiraan skor.""",
    llm_config=llm_config,
)

# 3. Membuat Agen 2: Reviewer Senior (Pengambil Keputusan Final)
reviewer = autogen.AssistantAgent(
    name="Reviewer_Senior",
    system_message="""Anda adalah Reviewer Senior. Anda akan membaca analisis dari Penilai_Utama.
    Setuju atau tidak setuju dengan analisis tersebut, tugas Anda adalah menetapkan skor final.
    ATURAN MUTLAK: Anda HANYA boleh membalas dengan satu angka digit (1, 2, 3, 4, 5, atau 6). Jangan berikan teks lain.""",
    llm_config=llm_config,
)

# 4. Membuat Agen 3: Admin (Pembuat Tugas)
admin = autogen.UserProxyAgent(
    name="Admin",
    human_input_mode="NEVER", # Biarkan agen berjalan otomatis tanpa input manusia
    max_consecutive_auto_reply=1,
    code_execution_config=False,
    is_termination_msg=lambda x: "TERMINATE" in x.get("content", "")
)

print("Agen berhasil disiapkan!")

Agen berhasil disiapkan!

### 2. Fungsi Eksekusi Diskusi Agen
Fungsi `jalankan_diskusi_agen` ini akan menginisiasi percakapan antara Admin, Penilai Utama, dan Reviewer Senior. Percakapan dibatasi maksimal 3 putaran agar efisien, dan di akhir percakapan, kita mengekstrak skor final dari Reviewer Senior.

In [2]:
def jalankan_diskusi_agen(esai_teks):
    # Membersihkan riwayat percakapan sebelumnya agar agen tidak bingung
    admin.clear_history()
    penilai.clear_history()
    reviewer.clear_history()
    
    # Memulai Group Chat
    groupchat = autogen.GroupChat(
        agents=[admin, penilai, reviewer], 
        messages=[], 
        max_round=3 # Dibatasi 3 putaran: Admin bertanya -> Penilai menjawab -> Reviewer memutuskan
    )
    
    manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)
    
    # Admin memulai instruksi
    pesan_awal = f"Tolong nilai esai ini: \n\n{esai_teks}"
    
    # Menjalankan percakapan (ini akan mencetak log diskusi ke layar)
    admin.initiate_chat(manager, message=pesan_awal)
    
    # Mengambil pesan terakhir dari percakapan (seharusnya ini adalah angka dari Reviewer_Senior)
    pesan_terakhir = admin.chat_messages[manager][-1]['content']
    
    # Ekstraksi angka untuk memastikan output bersih
    match = re.search(r'[1-6]', pesan_terakhir)
    if match:
        return int(match.group())
    return 3 # Fallback

### 3. Uji Coba Multi-Agent pada Sebagian Data Latih
Sebelum menjalankan pada data *test*, mari kita simulasikan diskusi antar agen pada 5 sampel data latih untuk melihat bagaimana agen-agen tersebut berinteraksi dan memberikan skor.

In [3]:
# Ingat untuk menyesuaikan path karena dataset sekarang ada di folder terpisah
df_train = pd.read_csv('../dataset/train.csv').head(5) 

prediksi_multi_agent = []

print("Memulai proses Multi-Agent pada 5 esai...")

for index, row in tqdm(df_train.iterrows(), total=df_train.shape[0]):
    esai = row['full_text']
    
    # Jalankan diskusi antar agen
    skor_final = jalankan_diskusi_agen(esai)
    prediksi_multi_agent.append(skor_final)

df_train['pred_multi_agent'] = prediksi_multi_agent

print("\nSimulasi selesai! Berikut hasilnya:")
display(df_train[['essay_id', 'score', 'pred_multi_agent']])

Memulai proses Multi-Agent pada 5 esai...

  0%|          | 0/5 [00:00<?, ?it/s]

Admin (to chat_manager):

Tolong nilai esai ini:

Many people have car where they live. The thing they don't know is that when you use a car alot of thing can happen like you can get in accidet or the smoke that the car has is bad to breath on if someone is walk but in VAUBAN,Germany they dont have that proble because 70 percent of vauban's families do not own cars,and 57 percent sold a car to move there. Street parkig ,driveways and home garages are forbidden on the outskirts of freiburd that near the French and Swiss borders. You probaly won't see a car in Vauban's streets because they are completely "car free" but If some that lives in VAUBAN that owns a car ownership is allowed,but there are only two places that you can park a large garages at the edge of the development,where a car owner buys a space but it not cheap to buy one they sell the space for you car for $40,000 along with a home. The vauban people completed this in 2006 ,they said that this an example of a growing trend in Europe,The untile states and some where else are suburban life from auto use this is called "smart planning". The current efforts to drastically reduce greenhouse gas emissions from tailes the passengee cars are responsible for 12 percent of greenhouse gas emissions in Europe and up to 50 percent in some car intensive in the United States. I honeslty think that good idea that they did that is Vaudan because that makes cities denser and better for walking and in VAUBAN there are 5,500 residents within a rectangular square mile. In the artical David Gold berg said that "All of our development since World war 2 has been centered on the cars,and that will have to change" and i think that was very true what David Gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in VAUBAN so people can see how we really don't need car to go to place from place because we can walk from were we need to go or we can ride bycles with out the use of a car. It good that they are doing that if you thik about your help the earth in way and thats a very good thing to. In the United states ,the Environmental protection Agency is promoting what is called "car reduced"communtunties,and the legislators are starting to act,if cautiously. Maany experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year. In previous bill,80 percent of appropriations have by law gone to highways and only 20 percent to other transports. There many good reason why they should do this.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:25:17] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:25:27] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Here's my analysis:

The essay has some grammatical errors and lacks cohesion in its structure. However, it does show a clear attempt to discuss the concept of "smart planning" and its benefits in reducing greenhouse gas emissions. The writer also provides specific examples from Vauban, Germany, which adds depth to their argument.

Score: 4 out of 6

The essay's strengths include its clear thesis statement and the use of specific examples to support it. However, it could be improved by addressing some grammatical errors and providing more transitions between paragraphs to improve cohesion.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:25:30] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:25:32] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (f5e12912-7aab-43a5-a81b-dfa56f8d61a5): Maximum rounds (3) reached

 20%|██        | 1/5 [00:22<01:30, 22.67s/it]

Admin (to chat_manager):

Tolong nilai esai ini:

I am a scientist at NASA that is discussing the "face" on mars. I will be explaining how the "face" is a land form. By sharing my information about this isue i will tell you just that.

First off, how could it be a martions drawing. There is no plant life on mars as of rite now that we know of, which means so far as we know it is not possible for any type of life. That explains how it could not be made by martians. Also why and how would a martion build a face so big. It just does not make any since that a martian did this.

Next, why it is a landform. There are many landforms that are weird here in America, and there is also landforms all around the whole Earth. Many of them look like something we can relate to like a snake a turtle a human... So if there are landforms on earth dont you think landforms are on mars to? Of course! why not? It's just unique that the landform on Mars looks like a human face. Also if there was martians and they were trying to get our attention dont you think we would have saw one by now?

Finaly, why you should listen to me. You should listen to me because i am a member of NASA and i've been dealing with all of this stuff that were talking about and people who say martians did this have no relation with NASA and have never worked with anything to relate to this landform. One last thing is that everyone working at NASA says the same thing i say, that the "face" is just a landform.

To sum all this up the "face" on mars is a landform but others would like to beleive it's a martian sculpture. Which every one that works at NASA says it's a landform and they are all the ones working on the planet and taking pictures.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:25:33] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:25:34] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:25:34] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:25:49] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Analisis:

Esai ini memiliki kelebihan dalam penggunaan bahasa yang sederhana dan mudah dipahami, serta struktur yang jelas dan logis. Penulis juga berhasil menjelaskan argumennya dengan menggunakan contoh-contoh yang relevan dan data yang didukung oleh pengetahuan tentang Mars. Namun, esai ini memiliki beberapa kekurangan, seperti penggunaan kalimat yang tidak efektif (misalnya "That explains how it could not be made by martians.") dan kurangnya analisis yang lebih dalam terhadap argumen-argumen.

Perkiraan skor: 4/6

Penulis telah melakukan baik dalam menjelaskan argumennya, tetapi perlu meningkatkan kualitas penggunaan bahasa dan analisis yang lebih dalam.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:25:50] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:25:52] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (e867a355-552a-4f7a-a839-0fe8df505d0e): Maximum rounds (3) reached

 40%|████      | 2/5 [00:42<01:02, 20.92s/it]

Admin (to chat_manager):

Tolong nilai esai ini:

People always wish they had the same technology that they have seen in movies, or the best new piece of technology that is all over social media. However, nobody seems to think of the risks that these kinds of new technologies may have. Cars have been around for many decades, and now manufacturers are starting to get on the bandwagon and come up with the new and improved technology that they hope will appeal to everyone. As of right now, it seems as though the negative characteristics of these cars consume the positive idea that these manufacturers have tried to convey.

Currently, this new technology in cars has a very long way to go before being completely "driverless". Drivers still need to be on alert when they are driving, as well as control the car near any accidents or complicated traffic situations. This seems to totally defeat the purpose of the "driverless" car. Eventually the technology may improve, but nobody can be certain that the driverless car will eventually become completely "driverless". This idea just seems like a lot of hard work and money for something that is not very neccessary. If someone does not want to drive their car they can just take a city bus or a subway. There are so many options of transportation that can already solve this problem. Even if masnufacturers are trying to make driving more "fun", driving is not meant to be "fun" it is meant to get people where they need to go. Playing around in a car just to have "fun" is just a recipe for disaster.

The idea of the driverless car also raises many questions about who will be liable when someone gets into an accident in one of these new cars. Many states do not even let people drive semi-automatic cars because there are not even laws that pertain to the liability of anyone who get into an accident while driving these type of cars. If these cars become more popular, states may pass new laws. However, this topic also raises questions about who is able to dictate whether or not it was the car or the human's fault for an accident. Since this technology is so new, there could be many problems with the car's system that nobody has even discovered since they have not drove the car themselves. If someone test drives this kind of car or even purchases one and they get into a crash not knowing what could possibly happen to them, they will want to sue the car manufacturer since they were not aware of any bugs in the car's system. These lawsuits can add up and eventually the manufactuers will be in a bunch of debt, which could cost them their whole idea of the driverless car.

The technology car manufacturers are trying to develope may just be a diasaster in the making. There are many alternative options of transportations if you do not feel like driving yourself, and these options are way less expensive than buying a brand new car. Although this technology is relatively new, we can not be certain that this new idea will even pay off in the end, it may just be a waste of money and time. Sometimes the newest technology is not the most benefical.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:26:48] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:26:48] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:26:48] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:27:02] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Analisis:

The essay presents a clear argument against the development of driverless cars, highlighting the risks and uncertainties surrounding this technology. The writer effectively uses examples to illustrate their points, such as the need for human intervention in complex traffic situations and the potential for lawsuits due to unknown system bugs. The language is straightforward and easy to follow, making it accessible to a general audience.

Tata bahasa: 4/6 (The essay has some minor errors in grammar and punctuation, but overall, the writing is clear and concise.)

Isi esai: 5/6 (The writer presents a well-structured argument with supporting examples, effectively conveying their concerns about the development of driverless cars.)

Perkiraan skor: 4.5/6

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:27:04] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:27:06] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

4

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (7f0cb5e2-fea5-437f-9d5e-92a0a09ce4ca): Maximum rounds (3) reached

 60%|██████    | 3/5 [01:56<01:30, 45.16s/it]

Admin (to chat_manager):

Tolong nilai esai ini:

We all heard about Venus, the planet without almost oxygen with earthquakes, erupting volcanoes and temperatures average over 800 degrees Fahrenheit but what if scientist project the futur into this planet ? Through this article, the author uses evidences appealing to reason and concession to make us realize why we should care about studying this planet so that people must give a chance to Venus.

Venus is the closest planet to Earth in terms density and size but has a really different climate. As it is evoked by the author:

( 3) "A thick atmosphere of almost 97 percent carbon dioxide blankets Venus. Even more challenging are the clouds of highly corrosive sulfuric acid in Venus’s atmosphere. On the planet’s surface, temperatures average over 800 degrees Fahrenheit....Beyond high pressure and heat, Venusian geology and weather present additional impediments like erupting volcanoes, powerful earthquakes, and frequent lightning strikes to probes seeking to land on its surface." The author uses of concession tell us what is the actual climate of Venus. He tell us the truth, he support the fact that studying Venus is a worthy pursuit but he also recognize that there's a danger present continuously. And because he support the idea of studying Venus, he proposes ways to study the planet and find a solution at a reasonable distance.

Venus is an inhospitable planet that can almost be considered as an impossible dwelling for humans. But for the author, that can't keep scientist to do their job (studying Venus) : (5) "NASA’s possible solution to the hostile conditions on the surface of Venus would allow scientists to float above the fray. Imagine a blimp-like vehicle hovering 30 or so miles above the roiling Venusian landscape. Just as our jet airplanes travel at a higher altitude to fly over many storms, a vehicle hovering over Venus would avoid the unfriendly ground conditions by staying up and out of their way. At thirty-plus miles above the surface, temperatures would still be toasty at around 170 degrees Fahrenheit, but the air pressure would be close to that of sea level on Earth." Through this evidence, appealing to reasonning, the author talk about the NASA's possible solution to raise his credibility. But also, to convince the audience that we can only find a solution by studying the planet.

In conclusion, despite of Venus hostility put in advance by the concession, the author makes the audience realize that there's a solution but that we can find it only if we study the planet. He make us find out that challenge and curiosity is part of human life. But also that danger and fear should not stop us from discovering new things. After all, we are Humans.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:27:53] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:27:54] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:27:54] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:28:00] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Analisis:

The essay demonstrates good use of concession to present a balanced view of Venus's hostile environment. The author effectively uses evidence and appealing to reason to make a convincing argument for the importance of studying Venus. The writing is clear and concise, with a logical flow of ideas.

Perkiraan skor: 5

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:28:02] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:28:03] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

6

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (9fd8010b-08ec-498d-b41b-379c203434da): Maximum rounds (3) reached

 80%|████████  | 4/5 [02:53<00:49, 49.99s/it]

Admin (to chat_manager):

Tolong nilai esai ini:

Dear, State Senator

This is a letter to argue in favor of keeping the Electoral College."There are many reasons to keep the Electoral College" one reason is because it is widely regarded as an anachronism, a dispute over the outcome of an Electoral College vote is possible, but it is less likely than a dispute over the popular vote, and the Electoral College restores some of the weight in the political balance that large states (by population) lose by virue of the mal apportionment of the Senate decreed in the Constitution.

I am in favor of keeping the Electoral College because,it is widely regarded as an anachronism. A non-democratic method of selecting a president that ought to be [overruled] by declaring the canaditdate who receives the most populare votes the winner. The advocates of this position are correct in arguing that the Electoral College method is not democratic in a method sense.It is the electors who elect the the president ,not the people. But each party selects a slate of electors trusted to vote for the party's nominee (and that trust is rarely betrayed).

Another, reason I am in favor of keeping the Electoral College is because, a dispute over the outcome of an Electoral College vote is possible. But it is less likely than a dispute over the popular vote. But it is less likely than a dispute over the popular vote. The reason is that the winning canadate's share of the Electoral College invariably exceeds his share of the popular vote.

Last but not least, I am in favor of keeping the Electoral College is because, the Electoral College restores some of the weight in the political balance that large states (by population) lose by virue of the mal apportionment of the Senate decreed in the Constitution. A larger state gets more attintion from presidential canadidates in a campaign than a small state does. It can be argued that Electoral College methods of selecting the president may turn off potential voters for a canadidates who has no hope of carrying their state. But of  course no voter's vote swings a national election, and in spite of that, about 1/2 the eligible American population did vote in the [2012's] election.

From, PROPER_NAME

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:28:04] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:28:05] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:28:05] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:28:23] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Analisis:

The essay presents a clear argument in favor of keeping the Electoral College system. The writer uses logical reasoning to support their stance, citing reasons such as the possibility of disputes over popular votes, the importance of large states' voices being heard, and the potential for candidates to focus on swing states rather than neglecting smaller ones. However, the essay could benefit from more nuanced exploration of counterarguments and a stronger conclusion that ties together the main points.

Tata bahasa:

The essay's language is generally clear and concise, with some minor errors in grammar and punctuation (e.g., "it is widely regarded as an anachronism" should be a separate sentence). The writer could improve their writing by using more varied sentence structures and avoiding repetitive phrases ("I am in favor of keeping the Electoral College because...").

Perkiraan skor: 4/6

The essay presents a clear argument, but it could benefit from more depth and nuance. The language is generally clear, but there are some minor errors that detract from the overall effectiveness of the writing.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:28:25] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:28:26] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (f6e1744f-2307-4e26-94fb-b6f0d9b31c2e): Maximum rounds (3) reached

100%|██████████| 5/5 [03:16<00:00, 39.36s/it]

Simulasi selesai! Berikut hasilnya:

  essay_id  score  pred_multi_agent
0  000d118      3                 5
1  000fe60      3                 5
2  001ab80      4                 4
3  001bdc0      4                 6
4  002ba53      3                 5

### 4. Eksekusi pada Data Uji (Test Data) dan Format Submission
Setelah sistem multi-agent terbukti berjalan dengan baik, kita terapkan pada seluruh data uji (`test.csv`). Hasil akhirnya (berupa skor) akan digabungkan ke dalam format yang sesuai untuk submission Kaggle (`submission_autogen.csv`).

In [4]:
# 1. Muat data test
df_test = pd.read_csv('../dataset/test.csv')

prediksi_final_autogen = []

print("Memerintahkan Multi-Agent untuk menilai data uji Kaggle...")

# 2. Looping ke seluruh data test
for index, row in tqdm(df_test.iterrows(), total=df_test.shape[0]):
    esai_target = row['full_text']
    
    # Jalankan diskusi antar agen untuk setiap esai
    skor_final = jalankan_diskusi_agen(esai_target)
    prediksi_final_autogen.append(skor_final)

# 3. Format hasil sesuai aturan submission Kaggle
submission_autogen = pd.DataFrame({
    'essay_id': df_test['essay_id'],
    'score': prediksi_final_autogen
})

# 4. Simpan ke dalam folder outputs
submission_autogen.to_csv('../outputs/submission_autogen.csv', index=False)

print("\nSukses Besar! File 'submission_autogen.csv' sudah jadi dan siap di-submit ke Kaggle!")
display(submission_autogen.head())

Memerintahkan Multi-Agent untuk menilai data uji Kaggle...

  0%|          | 0/3 [00:00<?, ?it/s]

Admin (to chat_manager):

Tolong nilai esai ini:

Many people have car where they live. The thing they don't know is that when you use a car alot of thing can happen like you can get in accidet or the smoke that the car has is bad to breath on if someone is walk but in VAUBAN,Germany they dont have that proble because 70 percent of vauban's families do not own cars,and 57 percent sold a car to move there. Street parkig ,driveways and home garages are forbidden on the outskirts of freiburd that near the French and Swiss borders. You probaly won't see a car in Vauban's streets because they are completely "car free" but If some that lives in VAUBAN that owns a car ownership is allowed,but there are only two places that you can park a large garages at the edge of the development,where a car owner buys a space but it not cheap to buy one they sell the space for you car for $40,000 along with a home. The vauban people completed this in 2006 ,they said that this an example of a growing trend in Europe,The untile states and some where else are suburban life from auto use this is called "smart planning". The current efforts to drastically reduce greenhouse gas emissions from tailes the passengee cars are responsible for 12 percent of greenhouse gas emissions in Europe and up to 50 percent in some car intensive in the United States. I honeslty think that good idea that they did that is Vaudan because that makes cities denser and better for walking and in VAUBAN there are 5,500 residents within a rectangular square mile. In the artical David Gold berg said that "All of our development since World war 2 has been centered on the cars,and that will have to change" and i think that was very true what David Gold said because alot thing we need cars to do we can go anyway were with out cars beacuse some people are a very lazy to walk to place thats why they alot of people use car and i think that it was a good idea that that they did that in VAUBAN so people can see how we really don't need car to go to place from place because we can walk from were we need to go or we can ride bycles with out the use of a car. It good that they are doing that if you thik about your help the earth in way and thats a very good thing to. In the United states ,the Environmental protection Agency is promoting what is called "car reduced"communtunties,and the legislators are starting to act,if cautiously. Maany experts expect pubic transport serving suburbs to play a much larger role in a new six years federal transportation bill to approved this year. In previous bill,80 percent of appropriations have by law gone to highways and only 20 percent to other transports. There many good reason why they should do this.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:31:41] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:31:55] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Analisis:

The essay has some grammatical errors and lacks cohesion in its structure. However, the writer shows a clear interest in the topic of car-free living and provides some interesting facts about Vauban, Germany. The writer also attempts to connect the concept of "smart planning" to the idea of reducing greenhouse gas emissions.

Perkiraan skor: 4

The essay has some potential, but it needs significant improvement in terms of grammar, sentence structure, and overall coherence. The writer's ideas are not fully developed, and there is a lack of supporting evidence or examples to back up their claims. However, the topic is interesting, and with further development and refinement, the essay could be improved.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:31:57] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:31:59] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (1cff25c8-e835-4dee-9e43-799d18dd4ea0): Maximum rounds (3) reached

 33%|███▎      | 1/3 [00:25<00:51, 25.58s/it]

Admin (to chat_manager):

Tolong nilai esai ini:

I am a scientist at NASA that is discussing the "face" on mars. I will be explaining how the "face" is a land form. By sharing my information about this isue i will tell you just that.

First off, how could it be a martions drawing. There is no plant life on mars as of rite now that we know of, which means so far as we know it is not possible for any type of life. That explains how it could not be made by martians. Also why and how would a martion build a face so big. It just does not make any since that a martian did this.

Next, why it is a landform. There are many landforms that are weird here in America, and there is also landforms all around the whole Earth. Many of them look like something we can relate to like a snake a turtle a human... So if there are landforms on earth dont you think landforms are on mars to? Of course! why not? It's just unique that the landform on Mars looks like a human face. Also if there was martians and they were trying to get our attention dont you think we would have saw one by now?

Finaly, why you should listen to me. You should listen to me because i am a member of NASA and i've been dealing with all of this stuff that were talking about and people who say martians did this have no relation with NASA and have never worked with anything to relate to this landform. One last thing is that everyone working at NASA says the same thing i say, that the "face" is just a landform.

To sum all this up the "face" on mars is a landform but others would like to beleive it's a martian sculpture. Which every one that works at NASA says it's a landform and they are all the ones working on the planet and taking pictures.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:32:00] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:32:01] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:32:01] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:32:20] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Analisis:

Esai ini memiliki kelebihan dalam penggunaan bahasa yang sederhana dan mudah dipahami, serta struktur yang jelas dan logis. Penulis juga berhasil mengembangkan argumennya dengan menggunakan contoh-contoh yang relevan dan data yang didukung oleh pengetahuan tentang NASA. Namun, esai ini memiliki beberapa kekurangan, seperti penggunaan kalimat yang tidak jelas (misalnya "That explains how it could not be made by martians.") dan beberapa kesalahan ejaan.

Perkiraan skor: 4/6

Penulis telah menunjukkan kemampuan untuk mengembangkan argumennya dengan baik, namun masih perlu ditingkatkan dalam penggunaan bahasa yang lebih jelas dan akurat.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:32:22] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:32:23] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (0cc9f95d-8156-4714-af7c-d4b633e6d3ae): Maximum rounds (3) reached

 67%|██████▋   | 2/3 [00:49<00:24, 24.70s/it]

Admin (to chat_manager):

Tolong nilai esai ini:

People always wish they had the same technology that they have seen in movies, or the best new piece of technology that is all over social media. However, nobody seems to think of the risks that these kinds of new technologies may have. Cars have been around for many decades, and now manufacturers are starting to get on the bandwagon and come up with the new and improved technology that they hope will appeal to everyone. As of right now, it seems as though the negative characteristics of these cars consume the positive idea that these manufacturers have tried to convey.

Currently, this new technology in cars has a very long way to go before being completely "driverless". Drivers still need to be on alert when they are driving, as well as control the car near any accidents or complicated traffic situations. This seems to totally defeat the purpose of the "driverless" car. Eventually the technology may improve, but nobody can be certain that the driverless car will eventually become completely "driverless". This idea just seems like a lot of hard work and money for something that is not very neccessary. If someone does not want to drive their car they can just take a city bus or a subway. There are so many options of transportation that can already solve this problem. Even if masnufacturers are trying to make driving more "fun", driving is not meant to be "fun" it is meant to get people where they need to go. Playing around in a car just to have "fun" is just a recipe for disaster.

The idea of the driverless car also raises many questions about who will be liable when someone gets into an accident in one of these new cars. Many states do not even let people drive semi-automatic cars because there are not even laws that pertain to the liability of anyone who get into an accident while driving these type of cars. If these cars become more popular, states may pass new laws. However, this topic also raises questions about who is able to dictate whether or not it was the car or the human's fault for an accident. Since this technology is so new, there could be many problems with the car's system that nobody has even discovered since they have not drove the car themselves. If someone test drives this kind of car or even purchases one and they get into a crash not knowing what could possibly happen to them, they will want to sue the car manufacturer since they were not aware of any bugs in the car's system. These lawsuits can add up and eventually the manufactuers will be in a bunch of debt, which could cost them their whole idea of the driverless car.

The technology car manufacturers are trying to develope may just be a diasaster in the making. There are many alternative options of transportations if you do not feel like driving yourself, and these options are way less expensive than buying a brand new car. Although this technology is relatively new, we can not be certain that this new idea will even pay off in the end, it may just be a waste of money and time. Sometimes the newest technology is not the most benefical.

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:33:14] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:33:15] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
[autogen.oai.client: 05-16 18:33:15] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Penilai_Utama

[autogen.oai.client: 05-16 18:33:28] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Penilai_Utama (to chat_manager):

Here's my analysis:

The essay presents a clear argument against the development of driverless cars, highlighting the risks and uncertainties surrounding this technology. The writer effectively uses examples to illustrate their points, such as the need for human intervention in complex traffic situations and the potential for lawsuits due to unknown bugs in the car's system. The writing is generally clear and concise, with a logical flow of ideas.

However, the essay could benefit from more nuanced analysis and consideration of counterarguments. Additionally, some sentences could be tightened up for better clarity and coherence.

Perkiraan skor: 4

(Note: I would give this essay a score of 4 out of 6, as it presents a clear argument and uses relevant examples to support its claims, but could benefit from more development and refinement.)

--------------------------------------------------------------------------------
[autogen.oai.client: 05-16 18:33:31] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.

Next speaker: Reviewer_Senior

[autogen.oai.client: 05-16 18:33:32] {746} WARNING - Model llama3 is not found. The cost will be 0. In your config_list, add field {"price" : [prompt_price_per_1k, completion_token_price_per_1k]} for customized pricing.
Reviewer_Senior (to chat_manager):

5

--------------------------------------------------------------------------------

>>>>>>>> TERMINATING RUN (43dc1312-6062-44f3-8b64-04184c5ba96f): Maximum rounds (3) reached

100%|██████████| 3/3 [01:58<00:00, 39.55s/it]

Sukses Besar! File 'submission_autogen.csv' sudah jadi dan siap di-submit ke Kaggle!

  essay_id  score
0  000d118      5
1  000fe60      5
2  001ab80      5